version: '3'
services:
  db:
    image: postgres
    environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: chef
     POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432"
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db