# Generated by Django 3.0.4 on 2020-03-29 21:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Banners_Visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_session', models.CharField(max_length=255)),
                ('banners_visited', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=10)),
                ('campaign_visited', models.IntegerField(verbose_name=django.db.models.fields.IntegerField)),
                ('time_visited', models.DateTimeField()),
            ],
        ),
    ]
