# Generated by Django 3.0.4 on 2020-03-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Banner_Clicked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_session', models.CharField(max_length=255)),
                ('banner_clicked', models.IntegerField()),
            ],
        ),
    ]
